name: Build and Test with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    # Checkout the current repository
    - name: Checkout source code
      uses: actions/checkout@v3

    # Build the server Docker image
    - name: Build server Docker image
      run: |
        docker build -t my-server:latest . 

    # Clone the python-zenoh-client repository for the test Docker image
    - name: Checkout test repository
      uses: actions/checkout@v3
      with:
        repository: ovidiu-vacaru/python-zenoh-client
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: main  # Explicitly set the branch name
        path: python-zenoh-client

    # Build the test Docker image
    - name: Build test Docker image
      run: |
        cd python-zenoh-client
        docker build -t my-tester:latest .

    # Run the test container and log output
    - name: Start test container and capture logs
      run: |
        docker run -d --network host --name my-tester-container my-tester:latest
        docker logs -f my-tester-container > test-log.txt 2>&1 &

    # Wait briefly for the test container initialization
    - name: Wait for test container initialization
      run: |
        sleep 10

    # Start the server container
    - name: Start server container
      run: |
        docker run -d --network host --name my-server-container my-server:latest

    # Wait for tests to complete
    - name: Wait for tests
      run: |
        docker wait my-tester-container || true

    # Print the test log
    - name: Print test log
      run: |
        cat test-log.txt

    # Stop and cleanup containers and images
    - name: Cleanup
      run: |
        docker stop my-server-container my-tester-container || true
        docker rm my-server-container my-tester-container || true
        docker rmi my-server:latest my-tester:latest || true
